apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: subtracker-secret
  namespace: subtracker
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: subtracker-secret
    creationPolicy: Owner
  data:
    - secretKey: NEXT_PUBLIC_SUPABASE_URL
      remoteRef:
        key: mfo/private/subtracker/secrets
        property: NEXT_PUBLIC_SUPABASE_URL
    - secretKey: NEXT_PUBLIC_SUPABASE_ANON_KEY
      remoteRef:
        key: mfo/private/subtracker/secrets
        property: NEXT_PUBLIC_SUPABASE_ANON_KEY
    - secretKey: NEXT_PUBLIC_STACK_API_URL
      remoteRef:
        key: mfo/private/subtracker/secrets
        property: NEXT_PUBLIC_STACK_API_URL
    - secretKey: NEXT_PUBLIC_STACK_PROJECT_ID
      remoteRef:
        key: mfo/private/subtracker/secrets
        property: NEXT_PUBLIC_STACK_PROJECT_ID
    - secretKey: NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY
      remoteRef:
        key: mfo/private/subtracker/secrets
        property: NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY
    - secretKey: STACK_SECRET_SERVER_KEY
      remoteRef:
        key: mfo/private/subtracker/secrets
        property: STACK_SECRET_SERVER_KEY
